name: refrigerator_project_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.5.2
  provider: ^6.0.5
  yaml: ^3.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_svg: ^2.0.3
  dropdown_textfield: ^1.0.8
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/ref/
    - pubspec.yaml
